apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: f51zsz8ul-nodejs 
  janus-idp.io/tekton: f51zsz8ul-nodejs
  backstage.io/kubernetes-id: f51zsz8ul-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: f51zsz8ul-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  