apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: f51zsz8ul-nodejs-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/f51zsz8ul-nodejs-gitops