apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: f51zsz8ul-nodejs
  janus-idp.io/tekton: f51zsz8ul-nodejs
  backstage.io/kubernetes-id: f51zsz8ul-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: f51zsz8ul-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
